languaje: ruby
rvm:
  - "2.0.0"

before_install:
  - gem update
  - gem install sinatra
  - gem install activerecord
  - gem install sinatra-activerecord
  - gem install rake
  - gem install test-unit
  - gem install rack-test
  - gem install rubocop
  - gem install simplecov
  - gem install selenium-webdriver
 
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rubocop
  - bundle exec rake

deploy:
  provider: heroku
  api_key: "cf320367-3332-4635-9c5f-e3c0db06b2d8"
